# Generated by Django 2.2.7 on 2019-11-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191113_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
    ]
